CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE SEQUENCE "ReceiveNO" AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE "SampleNO" AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE "WorkSheetNO" AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "Customer" (
    "CustomerId" text NOT NULL,
    "Name" text NULL,
    "Address" text NULL,
    "PhoneNumber" text NULL,
    "Email" text NULL,
    CONSTRAINT "PK_Customer" PRIMARY KEY ("CustomerId")
);

CREATE TABLE "Department" (
    "DepartmentID" text NOT NULL,
    "Name" text NULL,
    "HeaderName" text NULL,
    CONSTRAINT "PK_Department" PRIMARY KEY ("DepartmentID")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WorkSheet" (
    "WorkSheetID" uuid NOT NULL,
    "ReceiveNo" text NULL,
    "WorkSheetNo" text NULL,
    "CustomerId" text NULL,
    "ReceiveDate" timestamp without time zone NOT NULL,
    "Note" text NULL,
    "Status" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_WorkSheet" PRIMARY KEY ("WorkSheetID"),
    CONSTRAINT "FK_WorkSheet_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("CustomerId") ON DELETE RESTRICT
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "DisplayName" text NULL,
    "Role" text NULL,
    "DepartmentID" text NULL,
    "Title" text NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Department_DepartmentID" FOREIGN KEY ("DepartmentID") REFERENCES "Department" ("DepartmentID") ON DELETE RESTRICT
);

CREATE TABLE "Method" (
    "MethodID" uuid NOT NULL,
    "Name" text NULL,
    "Unit" text NULL,
    "Description" text NULL,
    "TurnArroundDay" integer NOT NULL,
    "DepartmentID" text NULL,
    CONSTRAINT "PK_Method" PRIMARY KEY ("MethodID"),
    CONSTRAINT "FK_Method_Department_DepartmentID" FOREIGN KEY ("DepartmentID") REFERENCES "Department" ("DepartmentID") ON DELETE RESTRICT
);

CREATE TABLE "Sample" (
    "SampleID" integer GENERATED BY DEFAULT AS IDENTITY,
    "SampleNo" integer NOT NULL DEFAULT (nextval('"SampleNO"')),
    "WorkSheetID" uuid NOT NULL,
    "Description" text NULL,
    "Weight" real NOT NULL,
    "Note" text NULL,
    "SealNumber" text NULL,
    "Status" integer NOT NULL DEFAULT 0,
    "Sampling" boolean NOT NULL,
    CONSTRAINT "PK_Sample" PRIMARY KEY ("SampleID"),
    CONSTRAINT "FK_Sample_WorkSheet_WorkSheetID" FOREIGN KEY ("WorkSheetID") REFERENCES "WorkSheet" ("WorkSheetID") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Token" (
    "TokenID" integer GENERATED BY DEFAULT AS IDENTITY,
    "RefreshToken" text NULL,
    "ExpireTime" timestamp without time zone NOT NULL,
    "UserId" text NULL,
    CONSTRAINT "PK_Token" PRIMARY KEY ("TokenID"),
    CONSTRAINT "FK_Token_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SampleMethodAssigment" (
    "SampleID" integer NOT NULL,
    "MethodID" uuid NOT NULL,
    "Result" text NULL,
    "ResultDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_SampleMethodAssigment" PRIMARY KEY ("SampleID", "MethodID"),
    CONSTRAINT "FK_SampleMethodAssigment_Method_MethodID" FOREIGN KEY ("MethodID") REFERENCES "Method" ("MethodID") ON DELETE CASCADE,
    CONSTRAINT "FK_SampleMethodAssigment_Sample_SampleID" FOREIGN KEY ("SampleID") REFERENCES "Sample" ("SampleID") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_DepartmentID" ON "AspNetUsers" ("DepartmentID");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Method_DepartmentID" ON "Method" ("DepartmentID");

CREATE INDEX "IX_Sample_WorkSheetID" ON "Sample" ("WorkSheetID");

CREATE INDEX "IX_SampleMethodAssigment_MethodID" ON "SampleMethodAssigment" ("MethodID");

CREATE INDEX "IX_Token_UserId" ON "Token" ("UserId");

CREATE INDEX "IX_WorkSheet_CustomerId" ON "WorkSheet" ("CustomerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211106154101_Start', '5.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE "Method" ADD "Target" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211106160201_AddTartgetToMethod', '5.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE "Method" RENAME COLUMN "Target" TO "Targets";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211107101352_ModifyMethodtargets', '5.0.7');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211107102312_ModifyMethodtarget2', '5.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE "Method" RENAME COLUMN "Targets" TO "Target";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211107111143_ModifyMethodtargetRollback', '5.0.7');

COMMIT;

START TRANSACTION;


            CREATE OR REPLACE FUNCTION createWorkSheetNo() returns trigger
	            LANGUAGE plpgsql
	            AS 
                    $$
                    BEGIN
                        NEW."WorkSheetNo" = 'WSN' || EXTRACT(YEAR FROM CURRENT_DATE)::text
                        || NEW."WorkSheetSequence"::text;
                        RETURN NEW;
                    END;
                    $$;
                

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211107112856_AddWorkSheetNOFunc', '5.0.7');

COMMIT;

